name: Compare Python AST with default branch
runs:
  using: composite
  steps:
  - uses: actions/checkout@v2
  - name: detect revision
    env:
      DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
    run: |
      if git log -1|grep -F '[compare_py_ast]'; then
          git fetch --unshallow
          echo "REF_REVISION=$(git merge-base origin/${DEFAULT_BRANCH} HEAD)" >> $GITHUB_ENV
      fi
  - uses: actions/setup-python@v2
    if: env.REF_REVISION != ''
  - name: checkout ref
    uses: actions/checkout@v2
    if: env.REF_REVISION != ''
    with:
      path: ref
      ref: ${{ env.REF_REVISION }}
  - name: checkout HEAD
    uses: actions/checkout@v2
    if: env.REF_REVISION != ''
    with:
      path: HEAD
  - name: take hash of ref
    if: env.REF_REVISION != ''
    run: |
      cd ref && find . -type f -name \*.py -exec python -c "import ast;import hashlib;import sys;print(hashlib.sha256(ast.dump(ast.parse(open(sys.argv[1]).read())).encode('utf-8')).hexdigest(), sys.argv[1])" {} \; > ../ref.hash
  - name: take hash of HEAD
    if: env.REF_REVISION != ''
    run: |
      cd HEAD && find . -type f -name \*.py -exec python -c "import ast;import hashlib;import sys;print(hashlib.sha256(ast.dump(ast.parse(open(sys.argv[1]).read())).encode('utf-8')).hexdigest(), sys.argv[1])" {} \; > ../HEAD.hash
  - name: compare
    if: env.REF_REVISION != ''
    run: |
      diff ref.hash HEAD.hash
