name: Compare Python AST with specified revision
inputs:
  revision:
    description: commit hash of the reference revision to be compared with HEAD
    required: true
runs:
  using: composite
  steps:
  - name: test inputs
    shell: bash
    run: |
      test -n "${{ inputs.revision }}"
  - uses: actions/setup-python@v2
  - name: checkout ref
    uses: actions/checkout@v2
    with:
      path: ref
      ref: ${{ inputs.revision }}
  - name: checkout HEAD
    uses: actions/checkout@v2
    with:
      path: HEAD
  - name: take hash of ref
    shell: bash
    run: |
      REF_HASH=$(mktemp)
      cd ref && find . -type f -name \*.py -exec python -c "import ast;import hashlib;import sys;print(hashlib.sha256(ast.dump(ast.parse(open(sys.argv[1]).read())).encode('utf-8')).hexdigest(), sys.argv[1])" {} \; > ${REF_HASH}
      echo "REF_HASH=${REF_HASH}" >> $GITHUB_ENV
  - name: take hash of HEAD
    shell: bash
    run: |
      HEAD_HASH=$(mktemp)
      cd HEAD && find . -type f -name \*.py -exec python -c "import ast;import hashlib;import sys;print(hashlib.sha256(ast.dump(ast.parse(open(sys.argv[1]).read())).encode('utf-8')).hexdigest(), sys.argv[1])" {} \; > ${HEAD_HASH}
      echo "HEAD_HASH=${HEAD_HASH}" >> $GITHUB_ENV
  - name: compare
    shell: bash
    run: |
      diff ${REF_HASH} ${HEAD_HASH}
