name: Compare Python AST with default branch
runs:
  using: composite
  steps:
  - uses: actions/setup-python@v2
  - name: checkout ref
    uses: actions/checkout@v2
    with:
      path: ref
      ref: ${{ env.REF_REVISION }}
  - name: checkout HEAD
    uses: actions/checkout@v2
    with:
      path: HEAD
  - name: take hash of ref
    shell: bash
    run: |
      cd ref && find . -type f -name \*.py -exec python -c "import ast;import hashlib;import sys;print(hashlib.sha256(ast.dump(ast.parse(open(sys.argv[1]).read())).encode('utf-8')).hexdigest(), sys.argv[1])" {} \; > ../ref.hash
  - name: take hash of HEAD
    shell: bash
    run: |
      cd HEAD && find . -type f -name \*.py -exec python -c "import ast;import hashlib;import sys;print(hashlib.sha256(ast.dump(ast.parse(open(sys.argv[1]).read())).encode('utf-8')).hexdigest(), sys.argv[1])" {} \; > ../HEAD.hash
  - name: compare
    shell: bash
    run: |
      diff ref.hash HEAD.hash
