version: 2
jobs:
  flake8:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: python setup.py flake8
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: python setup.py test
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: python setup.py bdist_wheel
      - run: python setup.py sdist
workflows:
  version: 2
  build_and_test:
    jobs:
      - flake8
      - test
      - build:
          requires:
              - flake8
              - test
