version: 2
jobs:
  flake8:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: python setup.py flake8
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: python setup.py test
workflows:
  version: 2
  build_and_test:
    jobs:
      - flake8
      - test
      - wait_all_tests:
          requires:
              - flake8
              - test
