name: Compare Python AST with specified revision
runs:
  using: composite
  steps:
  - uses: actions/checkout@v2
  - name: detect revision
    run: |
      echo "REF_REVISION=$(git log -1|sed -ne 's/.*\[compare_py_ast_with:\(.*\)\].*/\1/p'|head -1)" >> $GITHUB_ENV
  - name: parse revision
    if: contains(env.REF_REVISION, '~') || contains(env.REF_REVISION, '^')
    run: |
      git fetch --unshallow
      echo "REF_REVISION=$(git rev-parse ${REF_REVISION})" >> $GITHUB_ENV
  - uses: actions/setup-python@v2
    if: env.REF_REVISION != ''
  - name: checkout ref
    uses: actions/checkout@v2
    if: env.REF_REVISION != ''
    with:
      path: ref
      ref: ${{ env.REF_REVISION }}
  - name: checkout HEAD
    uses: actions/checkout@v2
    if: env.REF_REVISION != ''
    with:
      path: HEAD
  - name: take hash of ref
    if: env.REF_REVISION != ''
    run: |
      cd ref && find . -type f -name \*.py -exec python -c "import ast;import hashlib;import sys;print(hashlib.sha256(ast.dump(ast.parse(open(sys.argv[1]).read())).encode('utf-8')).hexdigest(), sys.argv[1])" {} \; > ../ref.hash
  - name: take hash of HEAD
    if: env.REF_REVISION != ''
    run: |
      cd HEAD && find . -type f -name \*.py -exec python -c "import ast;import hashlib;import sys;print(hashlib.sha256(ast.dump(ast.parse(open(sys.argv[1]).read())).encode('utf-8')).hexdigest(), sys.argv[1])" {} \; > ../HEAD.hash
  - name: compare
    if: env.REF_REVISION != ''
    run: |
      diff ref.hash HEAD.hash
