name: Compare Python ASTs

on: [push]

jobs:
  compare_with_revision:
    runs-on: ubuntu-latest
    steps:
    - uses: .github/actions/compare-py-ast-with
  compare_with_default_branch:
    runs-on: ubuntu-latest
    steps:
    - uses: .github/actions/compare-py-ast
